@startuml

package @hp/warp {
    class Application <<(S,#FF7700) Singleton>> {
      +{static}create()
      ----
      +name: String
      +data: Object
      -state: Object
      ....
      +start()
      +destroy()
      ....
      +use()
      +useConfig()
    }

    class Bus {
      +on()
      +once()
      +onRequest()
      +off()
      +wait()
      +request()
    }

    abstract Component {
      +{static} id: String
      +{static} defaults: Object
      ----
      +{abstract}init()
      +{abstract}start()
      +{abstract}afterStart()
      +{abstract}beforeDestroy()
      +{abstract}destroy()
      ----
      +{abstract}handlers: Object
      +{abstract}requests: Object
    }

    Application --> Bus: > uses
    Application *- Component: > has many
    Component --> Bus: > delegates
}

class ConcreteComponent {
  -someProperty
  +someMethod()
}

Component <|.up. ConcreteComponent

@enduml
